## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

In [0]:
%tensorflow_version 2.x

### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default


### Collect Data

In [363]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np

In [0]:
Iris_df = pd.read_csv( '/content/gdrive/My Drive/Classnotes/Iris.csv' )

In [0]:
prices_df = pd.read_csv( '/content/gdrive/My Drive/Classnotes/inClassMaterial/neuralnetwork/prices.csv' )

### Check all columns in the dataset

In [367]:
Iris_df.columns

Index(['Sepal Length (in cm)', 'Sepal Width in (cm)', 'Petal length (in cm)',
       'Petal width (in cm)', 'Class'],
      dtype='object')

In [368]:
prices_df.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

In [369]:
Iris_df.head()

Sepal Length (in cm)  Sepal Width in (cm)  ...  Petal width (in cm)        Class
0                   5.1                  3.5  ...                  0.2  Iris-setosa
1                   4.9                  3.0  ...                  0.2  Iris-setosa
2                   4.7                  3.2  ...                  0.2  Iris-setosa
3                   4.6                  3.1  ...                  0.2  Iris-setosa
4                   5.0                  3.6  ...                  0.2  Iris-setosa

[5 rows x 5 columns]

In [370]:
prices_df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

### Drop columns `date` and  `symbol`

In [0]:
prices_x = prices_df.drop(['date','symbol'],axis=1)

In [372]:
prices_x.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [0]:
X = prices_x.iloc[0:1000,]

In [374]:
X.shape

(1000, 5)

In [375]:
X['volume_in_mn'] = (X['volume']/1000000)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [376]:
X.head()

open       close         low        high     volume  volume_in_mn
0  123.430000  125.839996  122.309998  126.250000  2163600.0        2.1636
1  125.239998  119.980003  119.940002  125.540001  2386400.0        2.3864
2  116.379997  114.949997  114.930000  119.739998  2489500.0        2.4895
3  115.480003  116.620003  113.500000  117.440002  2006300.0        2.0063
4  117.010002  114.970001  114.089996  117.330002  1408600.0        1.4086

In [377]:
y=X['volume_in_mn']
X.drop(['volume','volume_in_mn'],axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [378]:
X.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [0]:
features=X.columns

In [380]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float64
close    1000 non-null float64
low      1000 non-null float64
high     1000 non-null float64
dtypes: float64(4)
memory usage: 31.4 KB


In [381]:
y.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume_in_mn, dtype: float64

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

#### Convert Training and Test Data to numpy float32 arrays


In [0]:
x_train=x_train.astype('float32')

In [0]:
x_test=x_test.astype('float32')

In [0]:
y_train=y_train.astype('float32')

In [0]:
y_test=y_test.astype('float32')

In [388]:
type(x_test)

pandas.core.frame.DataFrame

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
ss = StandardScaler()

In [0]:
x_scaled_train=ss.fit_transform(x_train)

In [392]:
x_scaled_train

array([[-0.83798766, -0.83376074, -0.83608633, -0.8361765 ],
       [-0.92453974, -0.92335117, -0.92182165, -0.92691714],
       [-0.9309704 , -0.93117946, -0.9281334 , -0.93452203],
       ...,
       [ 0.22757484,  0.19870356,  0.20606217,  0.22626649],
       [ 0.7969411 ,  0.74911946,  0.7548385 ,  0.7916238 ],
       [-0.24255177, -0.24733487, -0.23628977, -0.24765883]],
      dtype=float32)

In [0]:
#ytrain=ss.transform(x_scaled_train)
x_scaled_test=ss.transform(x_test)

In [0]:
x_scaled_train=x_scaled_train.astype('float32')

In [0]:
x_scaled_test=x_scaled_test.astype('float32')

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
w=tf.zeros(shape=(4,1))
b=tf.zeros(shape=(1))

In [397]:
w.dtype

tf.float32

In [398]:
w

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [399]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

2.Define a function to calculate prediction

In [0]:
@tf.function
def prediction(x_scaled_train,w,b):
    y_pred=tf.add(tf.matmul(x_scaled_train,w), b)
    return y_pred
     

3.Loss (Cost) Function [Mean square error]

In [0]:
@tf.function
def loss(y_pred,y_train):
  diff=y_train-y_pred
  sqr=tf.square(diff)
  avg=tf.reduce_mean(sqr)
  return avg

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def train(x_scaled_train, y_train, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x_scaled_train, w, b)
        current_loss = loss(y_train, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [403]:
x_scaled_train.dtype

dtype('float32')

In [404]:
for i in range(100):    
    w, b = train(x_scaled_train, y_train, w, b)
    print('Current Training Loss on iteration', i, loss(y_train, prediction(x_scaled_train, w, b)).numpy())

Current Training Loss on iteration 0 202.14075
Current Training Loss on iteration 1 201.16193
Current Training Loss on iteration 2 200.22177
Current Training Loss on iteration 3 199.31895
Current Training Loss on iteration 4 198.45178
Current Training Loss on iteration 5 197.61913
Current Training Loss on iteration 6 196.81932
Current Training Loss on iteration 7 196.05132
Current Training Loss on iteration 8 195.31358
Current Training Loss on iteration 9 194.60516
Current Training Loss on iteration 10 193.92477
Current Training Loss on iteration 11 193.27126
Current Training Loss on iteration 12 192.64368
Current Training Loss on iteration 13 192.041
Current Training Loss on iteration 14 191.46208
Current Training Loss on iteration 15 190.90605
Current Training Loss on iteration 16 190.37222
Current Training Loss on iteration 17 189.85934
Current Training Loss on iteration 18 189.36694
Current Training Loss on iteration 19 188.89398
Current Training Loss on iteration 20 188.43968
Curr

### Get the shapes and values of W and b

In [405]:
w.numpy()

array([[-1.5554249e-08],
       [ 9.7672392e-10],
       [ 6.2759526e-09],
       [ 2.8782528e-08]], dtype=float32)

In [406]:
w.shape

TensorShape([4, 1])

In [407]:
b.numpy()

array([4.400352], dtype=float32)

In [408]:
b.shape

TensorShape([1])

### Model Prediction on 1st Examples in Test Dataset

In [409]:
prediction(x_scaled_test,w,b)

<tf.Tensor: shape=(200, 1), dtype=float32, numpy=
array([[4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],
       [4.400352],


## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
Iris_df = pd.read_csv( '/content/gdrive/My Drive/Classnotes/Iris.csv')

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
#from sklearn.preprocessing import LabelEncoder
#le=LabelEncoder()
#Iris_df['Class']=le.fit_transform(Iris_df['Class'])
Iris_df=pd.get_dummies(Iris_df,drop_first=False)

In [412]:
Iris_df.sample(5)

Sepal Length (in cm)  ...  Class_Iris-virginica
20                    5.4  ...                     0
28                    5.2  ...                     0
118                   7.7  ...                     1
127                   6.1  ...                     1
1                     4.9  ...                     0

[5 rows x 7 columns]

### Splitting the data into feature set and target set

In [0]:
X=Iris_df.drop(['Class_Iris-setosa','Class_Iris-versicolor','Class_Iris-virginica'],axis=1)
Y=Iris_df[['Class_Iris-setosa','Class_Iris-versicolor','Class_Iris-virginica']]

In [0]:
X=X.iloc[0:,]
Y=Y.loc[0:,]

In [415]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
Sepal Length (in cm)    150 non-null float64
Sepal Width in (cm)     150 non-null float64
Petal length (in cm)    150 non-null float64
Petal width (in cm)     150 non-null float64
dtypes: float64(4)
memory usage: 4.8 KB


In [0]:
x_train_iris,x_test_iris,y_train_iris,y_test_iris=train_test_split(X,Y,test_size=0.2,random_state=3)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function 

In [0]:
model=tf.keras.models.Sequential()

In [0]:
model.add(tf.keras.layers.BatchNormalization(input_shape=(4,)))

In [0]:
model.add(tf.keras.layers.Dense(3,activation='softmax'))

In [0]:
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

### Model Training 

In [421]:
model.fit(x_train_iris,y_train_iris,epochs=100,validation_data=(x_test_iris,y_test_iris))

Train on 120 samples, validate on 30 samples
Epoch 1/100
120/120 [==============================] - 0s 3ms/sample - loss: 1.0490 - accuracy: 0.3833 - val_loss: 3.3809 - val_accuracy: 0.3333
Epoch 2/100
120/120 [==============================] - 0s 178us/sample - loss: 1.0041 - accuracy: 0.4333 - val_loss: 3.1071 - val_accuracy: 0.3333
Epoch 3/100
120/120 [==============================] - 0s 158us/sample - loss: 0.9774 - accuracy: 0.4417 - val_loss: 2.8531 - val_accuracy: 0.3333
Epoch 4/100
120/120 [==============================] - 0s 191us/sample - loss: 0.9521 - accuracy: 0.4917 - val_loss: 2.6318 - val_accuracy: 0.3333
Epoch 5/100
120/120 [==============================] - 0s 141us/sample - loss: 0.9353 - accuracy: 0.5083 - val_loss: 2.4354 - val_accuracy: 0.3333
Epoch 6/100
120/120 [==============================] - 0s 153us/sample - loss: 0.9084 - accuracy: 0.5417 - val_loss: 2.2608 - val_accuracy: 0.3333
Epoch 7/100
120/120 [==============================] - 0s 158us/sample - lo

### Model Prediction

In [422]:
model.predict(x_test_iris)

array([[9.0951771e-01, 8.5370637e-02, 5.1116967e-03],
       [8.8457090e-01, 1.0866427e-01, 6.7647793e-03],
       [9.1694230e-01, 7.6688483e-02, 6.3692583e-03],
       [8.6101884e-01, 1.2970920e-01, 9.2719318e-03],
       [9.9414402e-01, 4.7805021e-03, 1.0754565e-03],
       [8.5416174e-04, 6.5885536e-02, 9.3326026e-01],
       [6.0827240e-02, 6.5912217e-01, 2.8005055e-01],
       [9.2890114e-01, 6.6723309e-02, 4.3755118e-03],
       [1.8209733e-02, 2.0335221e-01, 7.7843803e-01],
       [1.5716682e-01, 3.3294219e-01, 5.0989097e-01],
       [1.7768560e-01, 4.6005359e-01, 3.6226085e-01],
       [8.4807259e-01, 1.4586550e-01, 6.0619446e-03],
       [9.9892847e-02, 5.8029652e-01, 3.1981063e-01],
       [3.7438668e-02, 7.1125138e-01, 2.5130999e-01],
       [7.3085683e-03, 2.5442791e-01, 7.3826355e-01],
       [9.4785804e-01, 4.8746433e-02, 3.3955155e-03],
       [2.6316576e-02, 4.0582132e-01, 5.6786209e-01],
       [4.4215363e-03, 1.2179830e-01, 8.7378019e-01],
       [7.2998633e-03, 5.332

In [423]:
model.predict_classes(x_test_iris)

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 0, 2, 2,
       2, 2, 0, 2, 2, 1, 1, 2])

In [424]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_5 (Batch (None, 4)                 16        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
Total params: 31
Trainable params: 23
Non-trainable params: 8
_________________________________________________________________


### Save the Model

In [425]:
model.save('R6_External_Lab_Updated_Gurgaon_v1.pynb')

INFO:tensorflow:Assets written to: R6_External_Lab_Updated_Gurgaon_v1.pynb/assets


### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?